### PR TITLE
DesCert ontology

### PR DESCRIPTION
**Pull request by bhatt111**
First draft of DesCert ontology overlay.

### CODE REVIEW

**Comment by glguy** [comment]
This PR is using many cases of `describes with a single value of type` which means there must be exactly 1 of that value.

This is in (unfortunate) contrast to a top-level statement that `someProperty has a single value.` which means 0 or 1, optional.

We very recently fixed a couple of instances of this situation in #346 .

You might change some of these to:

```
prop describes Class with values of type Type.
prop describes Class with at most 1 value.
```

**Comment by bhatt111** [comment]
Hi Eric,
I made changes per your suggestion. Thanks. One additional question I have: I am defining new properties like _sallyUserGuide_, _radlUserGuide_, etc. I am thinking of using a single property name _userGuide_ for these. Is the is the right thing to do?
Devesh

**Comment by bhatt111** [comment]
I made some properties common across multiple classes: userGuide, semantics. More clean up of "single value" usage.

**Comment by bhatt111** [comment]
Added Daikon ontology to DesCertOntology.

**Comment by bhatt111** [comment]
The push 29563e5 just went through when I re-pushed it. This is for adding the Daikon ontology to DesCert.sadl.

**Pull request merged**
