### PR TITLE
Generate new OWL files

### PR DESCRIPTION
**Pull request by tuxji**
## Remove some unneeded files

.gitattributes: Don't display changes to SadlImplicitModel.owl, configuration.rdf, and ont-policy.rdf in OwlModels folders since their diffs aren't worth looking at.

RACK-Ontology/Graphs/GenerateCSV.owl.svg: Remove since GenerateCSV.sadl no longer exists.

RACK-Ontology/OwlModels/.gitignore: Remove since its patterns specify OWL files already in git, which makes them ineffective anyway.

RACK-Ontology/OwlModels/GenerateCSV.rules: Remove since GenerateCSV.sadl no longer exists.

RACK-Ontology/OwlModels/GenerateCSVQueries.rules: Remove since GenerateCSVQueries.sadl no longer exists.

RACK-Ontology/OwlModels/catalog-v001.xml - Remove since it's out of date, we can't regenerate it, and we probably don't need it.

RACK-Ontology/OwlModels/map.txt: Remove since it's just a list of filenames and we don't need it.

RACK-Ontology/OwlModels/ont-policy.rdf: Remove *.metrics.owl files which no longer exist.

tools/SysAssurance/.project: Remove since this isn't really a true SADL project (the only real source file in the entire directory tree is defaults.owl).

tools/SysAssurance/*: Remove every file except defaults.owl since they aren't real source files.

tools/SysAssurance/OwlModels/defaults.owl: Move it up one directory to make it easier to find the only real source file.

## Regenerate ImplicitModel/OwlModels files using SADL IDE

Using SADL IDE built from development branch, import all SADL projects and regenerate all ImplicitModel and OwlModels files to make it easier to inspect future changes made by SADLCli.

**/SadlBuiltinFunctions.sadl - Regenerate using SADL IDE.  Lines using "com.ge.research.sadl.jena.reasoner.builtin#..." now use "com.naturalsemantics.sadl.jena.reasoner.builtin#..." instead.

**/SadlImplicitModel.sadl - Regenerate using SADL IDE.  A statement that used to be at line 34 is now gone (this was a change made in the SADL development branch). 
34: augTypeUnits describes AugmentedType with a single value of type string List.

LM-Ontology/ImplicitModel/SadlImplicitModel.sadl - Also had a different statement at line 21, now the same as the other SadlImplicitModel.sadl files.
 -{Java, Python, Text, OtherLanguage} are types of Language.
 +{Java, Python, Text, OtherLanguage} are instances of Language.

The following projects didn't have all files in OwlModels completely added to git before, so add rest of files to git as well:
 - Boeing-Ontology
 - GE-Ontology
 - GrammaTech-Ontology
 - LM-Ontology
 - Provenance-Example
 - SRI-Ontology
 - STR-Ontology
 - Turnstile-Example/Turnstile-IngestionPackage/CounterApplicationUnitTesting

## Regenerate OWL files with SADLCli Docker image

Run SADLCli Docker image on all RACK projects with `docker run --rm -v $HOME/ARCOS/RACK:/RACK sadl/sadl-eclipse:dev -importAll /RACK -cleanBuild` to regenerate the OWL files.  Build fails with 45 errors in CounterApplicationUnitTesting.sadl just like it does in the SADL IDE.

Boeing.owl: Changes/deletions of some namespace prefixes.
GE.owl: Changes/deletions of some namespace prefixes.
GrammaTech.owl: Changes/deletions of some namespace prefixes.
LM.owl: Changes/deletions of some namespace prefixes.
SRI.owl: Changes/deletions of some namespace prefixes.
STR.owl: Changes/deletions of some namespace prefixes.

SadlImplicitModel.owl, configuration.rdf, ont-policy.rdf: Changes due to indeterminate ordering or filenames, not worth paying attention to.

## Regenerate OWL files with SADLCli Docker image again

Run SADLCli Docker image on all RACK projects with `docker run --rm -v $HOME/ARCOS/RACK:/RACK sadl/sadl-eclipse:dev -importAll /RACK -cleanBuild` a second time.  Build fails with 45 errors in CounterApplicationUnitTesting.sadl again.

Boeing.owl: Changes/additions of some namespace prefixes.
GE.owl: Changes/additions of some namespace prefixes.
GrammaTech.owl: Changes/additions of some namespace prefixes.
LM.owl: Changes/additions of some namespace prefixes.
SRI.owl: Changes/additions of some namespace prefixes.
STR.owl: Changes/additions of some namespace prefixes.

SadlImplicitModel.owl: Changes due to indeterminate ordering, not worth paying attention to.

## Fix 45 errors in CounterApplicationUnitTesting.sadl

Run SADLCli Docker image on all RACK projects with `docker run --rm -v $HOME/ARCOS/RACK:/RACK sadl/sadl-eclipse:dev -importAll /RACK -cleanBuild` after editing 15 lines in CounterApplicationUnitTesting.sadl to make 45 SADL errors go away.  Now build completes successfully.

**/SadlImplicitModel.owl: Changes due to indeterminate ordering, not worth paying attention to.

**/ont-policy.rdf: Changes due to indeterminate ordering, not worth paying attention to.

CounterApplicationUnitTesting.owl: Changes due to editing of 15 lines in source file.

CounterApplicationUnitTesting.sadl: Edit 15 lines, replacing:
- executedBy      with wasGeneratedBy
- executedOn      with wasAssociatedWith
- tst:developedBy with wasAssociatedWith
- tst:producedBy  with wasGeneratedBy

## Start generating OWL files in GitHub Actions workflows

download/action.yml: Generate OWL files before packaging RACK ontology files.

### CODE REVIEW

**Comment by tuxji** [comment]
All the checks have passed and the workflow logs look good.  The next step is for @AbhaMoitra @glguy @kityansiu or anyone else to review this pull request and confirm the pull request looks good to you too.  Please pay special attention to `Turnstile-Example/Turnstile-IngestionPackage/CounterApplicationUnitTesting/ontology/CounterApplicationUnitTesting.sadl` (a recent pull request removed some ontology relations such as `developedBy` and `executedBy` without updating this file, so I had to update it myself to fix some SADL errors).  The good news is that SADLCli found these SADL errors and would have failed the build for us if I hadn't fixed these SADL errors.

After I get a +1 and merge this pull request, the rack-box:dev docker image will have automatically generated OWL files replacing the original OWL files stored in git.  We will be able to remove the original OWL files from git after we've tested the rack-box:dev image a day or two.

**Comment by AbhaMoitra** [comment]
Thanks @tuxji. @kityansiu will be testing this out.

**Comment by tuxji** [comment]
Actually, this is only a pull request. I still need to merge this pull request before a rack-box dev image can be generated for testing.  I just want someone else to look it over and give me a +1 before I merge the pull request.

**Comment by kityansiu** [comment]
I think it looks good. I reviewed `CounterApplicationUnitTesting.sadl` which looks good. 

What I did was I ingested all the new owl files into my RACK-box. I then tried to load one of the nodegroups from the store. I get the following:
Annotation 2021-11-30 135517
 **rationale**: "nodeGroupService/inflateAndValidate threw java.lang.IllegalArgumentException No enum constant com.ge.research.semtk.sparqlX.XSDSupportedType.ANYURI\njava.base/java.lang.Enum.valueOf(Enum.java:240)\ncom.ge.research.semtk.sparqlX.XSDSupportedType.valueOf(XSDSupportedType.java:24)\ncom.ge.research.semtk.sparqlX.XSDSupportedType.getMatchingValue(XSDSupportedType.java:66)\n..."
 
Is this something we need to look into before merging?

**Comment by tuxji** [comment]
My hypothesis is that you got that error message because there were changes to the SADL files that impact the nodegroup CSV and JSON files, so we need to generate new nodegroup CSV and JSON files too.  It could well be something else too, but that's what I think.  Shall I merge this pull request so we can get my changes integrated too, and then Paul and I can start generating the new CDR files (manually first, then automatically as well)?

**Comment by kityansiu** [comment]
+1

**Pull request merged**
