### PR TITLE
Added SACM in new LM-Ontology dir. Removed SACM-S.

### PR DESCRIPTION
**Pull request by carter-e-veldhuizen**
Added SACM (formerly SACM-LM) in a new dir `LM-Ontology`, located within the top level directory. Also removed `SACM-S` (and it's associated OWL file) from the RACK Ontologies.

If a different location for the SACM ontology is desired, or if handling the SACM-S deletion as a separate pull request is preferred, please say so.

### CODE REVIEW

**Comment by AbhaMoitra** [comment]
We need to remove SACM-S from GeneratePropInfocsv.sadl and rerun it (to generate files in Data dir). Have not looked at the changes yet.

**Comment by kityansiu** [comment]
Just some high level comments on LM-Ontology:

- In Eclipse, you set the LM-Ontology project to reference RACK-Ontology. Right click on LM-Ontology -> Properties -> Project References. Tick the check box "RACK-Ontology"
Capture
- Clean the project. Add the generated .project file to the repo.
- Our convention is camel casing for properties. For example, 
   - HAS_VALUE -> hasValue
   - EXPRESSES -> expresses

**Comment by carter-e-veldhuizen** [comment]
> 
> 
> Just some high level comments on LM-Ontology:
> 
>     * In Eclipse, you set the LM-Ontology project to reference RACK-Ontology. Right click on LM-Ontology -> Properties -> Project References. Tick the check box "RACK-Ontology"
>       Capture
> 
>     * Clean the project. Add the generated .project file to the repo.
> 
>     * Our convention is camel casing for properties. For example,
>       
>       * HAS_VALUE -> hasValue
>       * EXPRESSES -> expresses

1. I've made significant updates to the match the style conventions.

2. I am unable to flag the Properties, as described, probably because I am using the SADL web-IDE, not Eclipse. The Ecplise plugin has consistently failed to work properly on my machine, so I've been forced to use the web-IDE. If there is a way of accomplishing this in the web-IDE, I will gladly do so.

3. `.project` files are explicitly excluded via the top level `.gitignore` file in the repo. Am I understanding correctly that I should override this behavior and push the `.project` file, anyways?

**Comment by kityansiu** [comment]
I just noticed that SACM has ACTIVITY, but we also have ACTIVITY in PROV-S. There is also an overlap between startTime & endTime and startedAtTime & endedAtTime. @glguy and @AbhaMoitra can advise on best way to resolve.
Capture

**Pull request merged**
