### PR TITLE
Combine RACK workflow files

### PR DESCRIPTION
**Pull request by tuxji**
Strictly speaking, we don't need separate workflow files for jobs that
share the same trigger conditions.  Such jobs can go in the same
workflow file, so let's reduce the number of separate workflow files
to only two (continuous.yml for continuous lint, test, and build jobs
and release.yml for release build jobs).

### CODE REVIEW

**Comment by tuxji** [comment]
@langston-barrett Can you take a look at the test job's output?  Especially https://github.com/ge-high-assurance/RACK/pull/239/checks?check_run_id=1488050269#step:11:119 which seems to show that a test failed, yet the test job itself still succeeded.  Was the test supposed to fail but the test job still succeed?

**Comment by langston-barrett** [comment]
@tuxji The "x" there denotes an expected failure, fixing the underlying problem is on my TODO list (see #193).

Here's where the test is marked as an expected failure: https://github.com/ge-high-assurance/RACK/blob/fee08f6cb2da43a093f33f10ee9d6f56f917e62f/tests/test_invariant_nodegroups.py#L7

**Review by langston-barrett — APPROVED** [review]
LGTM, assuming that none of the individual steps changed.

Two questions:

- Are these run serially or in parallel?
- Is the filesystem shared between them? Would it be possible to share any resources (e.g. `pip` cache) between steps?

**Comment by tuxji** [comment]
The individual steps haven't changed.  The jobs themselves have been combined or moved from multiple files to one file, but the following invariants still are true of the jobs:

The jobs run in parallel (even if defined together in the same file).

The jobs don't share the same filesystem (each job runs in its own virtual machine).

I don't know if the lint job can share the same pip cache as the other jobs because its requirement.txt file is different than the other jobs' requirement.txt file.  What is the reason for having two different files (cli/requirement.txt and cli/dev/requirement.txt)?

**Comment by langston-barrett** [comment]
Thanks, that all makess sense.

> What is the reason for having two different files (cli/requirement.txt and cli/dev/requirement.txt)?

`cli/requirements.txt` lists the runtime dependencies of the `rack` package, whereas `dev/requirements.txt` lists tools that are used by *developers* of the `rack` package (e.g. linting tools).

**Pull request merged**
