### PR TITLE
Initial claims ontology

### PR DESCRIPTION
**Pull request by glguy**

### CODE REVIEW

**Review by bhatt111 — CHANGES_REQUESTED** [review]
partiallySupports should be an attribute of PROPERTY_TYPE, not of PROPERTY, since that determination is made for the PROPERTY_TYPE. We need to think of PROPERTY_TYPE as a first class ENTITY, rather that just an "enumeration". We will still have predefined identifiers in SADL for PROPERTY_TYPE for he enumeration.

**Comment by glguy** [comment]
> partiallySupports should be an attribute of PROPERTY_TYPE, not of PROPERTY, since that determination is made for the PROPERTY_TYPE. We need to think of PROPERTY_TYPE as a first class ENTITY, rather that just an "enumeration". We will still have predefined identifiers in SADL for PROPERTY_TYPE for he enumeration.

I'm expecting the PROPERTY_TYPEs to exist in the ontology before any OBJECTIVES are ever added. Would it make sense for OBJECTIVES to point to PROPERTY_TYPE, perhaps?

**Comment by bhatt111** [comment]
Eric,
I was just going to modify this comment based upon discussion with Vatsan this morning. The "partiallySupports" attribute has been in the PROPERTY class (and not used) long before the new approach with CLAIMS was proposed.  I agree with you it doesn't belong in PROPERTY_TYPE, but neither does it belong in PROPERTY or OBJECTIVE. Our understanding is that it belongs in CLAIM, which can support specific OBJECTIVE(s) based upon the PROPERTY(s) and THEORY the claim uses. E.g., one can write claims to support different objectives using overlapping sets of properties.
Devesh

From: Eric Mertens ***@***.***>
Sent: Friday, October 28, 2022 12:05 PM
To: ge-high-assurance/RACK ***@***.***>
Cc: Bhatt, Devesh (AdvTech) ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [ge-high-assurance/RACK] Initial claims ontology (PR #804)

WARNING: This message has originated from an External Source. This may be a phishing email that can result in unauthorized access to Honeywell systems. Please use proper judgment and caution when opening attachments, clicking links or responding.

partiallySupports should be an attribute of PROPERTY_TYPE, not of PROPERTY, since that determination is made for the PROPERTY_TYPE. We need to think of PROPERTY_TYPE as a first class ENTITY, rather that just an "enumeration". We will still have predefined identifiers in SADL for PROPERTY_TYPE for he enumeration.

I'm expecting the PROPERTY_TYPEs to exist in the ontology before any OBJECTIVES are ever added. Would it make sense for OBJECTIVES to point to PROPERTY_TYPE, perhaps?

-

**Comment by glguy** [comment]
All of the claims types have been incorporated into the enumeration variant CSVs. I recommend using the [...] menu to select View File to get a pretty table view in the PR changed files tab.

We've instantiated the claims diagram with example bits from each of the contributing teams claims information.

Note that the "source" column in these CSV files are simply for reference as we iterate on this design. They are not going to be loaded into RACK itself.

Screen Shot 2022-10-28 at 4 58 46 PM
Screen Shot 2022-10-28 at 4 58 55 PM
Screen Shot 2022-10-28 at 4 59 08 PM

**Comment by glguy** [comment]
@bhatt111 we've moved `partiallySupports` over to a CLAIM per discussion today.

**Comment by glguy** [comment]
@bhatt111 I've incorporated your changes to the SRI overlay

**Comment by kityansiu** [comment]
I just noticed that with the new claim enumeration types, we now have CWEs added as both [PROPERTY_TYPES](https://github.com/ge-high-assurance/RACK/blob/claims/RACK-Ontology/ontology/claims/PROPERTY_TYPES.csv) and [MITRE-CWE](https://github.com/ge-high-assurance/RACK/blob/claims/RACK-Ontology/ontology/MITRE-CWE/MITRE_CWE.csv). Is this really what we want? Should we remove one of them?

**Comment by bhatt111** [comment]
I believe the CWE's may have been added as PROPERTY_TYPES<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fge-high-assurance%2FRACK%2Fblob%2Fclaims%2FRACK-Ontology%2Fontology%2Fclaims%2FPROPERTY_TYPES.csv&data=05%7C01%7Cdevesh.bhatt%40honeywell.com%7C46de96b669b745c9d64d08dac0d62650%7C96ece5269c7d48b08daf8b93c90a5d18%7C0%7C0%7C638034323264531535%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NlD6GuIrnmxsz8kwTEQJk5d%2FWu7g%2Bb3Z92Pv1EXtbR0%3D&reserved=0> by Lockheed, bit by SRI team.
Devesh

From: Kit Siu ***@***.***>
Sent: Monday, November 7, 2022 9:39 AM
To: ge-high-assurance/RACK ***@***.***>
Cc: Bhatt, Devesh (AdvTech) ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [ge-high-assurance/RACK] Initial claims ontology (PR #804)

WARNING: This message has originated from an External Source. This may be a phishing email that can result in unauthorized access to Honeywell systems. Please use proper judgment and caution when opening attachments, clicking links or responding.

I just noticed that with the new claim enumeration types, we now have CWEs added as both PROPERTY_TYPES<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fge-high-assurance%2FRACK%2Fblob%2Fclaims%2FRACK-Ontology%2Fontology%2Fclaims%2FPROPERTY_TYPES.csv&data=05%7C01%7Cdevesh.bhatt%40honeywell.com%7C46de96b669b745c9d64d08dac0d62650%7C96ece5269c7d48b08daf8b93c90a5d18%7C0%7C0%7C638034323264531535%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NlD6GuIrnmxsz8kwTEQJk5d%2FWu7g%2Bb3Z92Pv1EXtbR0%3D&reserved=0> and MITRE-CWE<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fge-high-assurance%2FRACK%2Fblob%2Fclaims%2FRACK-Ontology%2Fontology%2FMITRE-CWE%2FMITRE_CWE.csv&data=05%7C01%7Cdevesh.bhatt%40honeywell.com%7C46de96b669b745c9d64d08dac0d62650%7C96ece5269c7d48b08daf8b93c90a5d18%7C0%7C0%7C638034323264531535%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vCC1WB90pfNy1mLrtD4IFvtlXZTx13xpJC8SuiHX4GU%3D&reserved=0>. Is this really what we want? Should we remove one of them?

-

**Comment by glguy** [comment]
@kityansiu I agree that it's not great that the CWEs are duplicated.

Maybe another encoding would just be to have a single "CWE present in module" property and require the claim to use "addresses" to point the the actual MITRE_CWE instance.

**Pull request merged**
