### PR TITLE
migration tool

### PR DESCRIPTION
**Pull request by Ptival**
This commit implements a migration tool for nodegroups across ontology changes.

Changes are listed in the rack/commits/ subfolder.  The type of changes we
currently support are listed in the ontology_changes/ directory.

Support may still be partial, but the tool does a lot of the tedious work.

### CODE REVIEW

**Comment by Ptival** [comment]
@russell-d-e If you'd like to give this a try, this is the branch and I wrote a minimal instructional README.

Let me know if anything is confusing or not working!

**Comment by kityansiu** [comment]
@russell-d-e or @cuddihyge, can you guys review and merge? I'd like to get this into v5.1. Target is Monday, 3/29, noon so @tuxji can make a cut of the release. Thanks!

**Comment by GregIthaca** [comment]
I have a few questions about the migration tool.

1. The documentation says it will only migrate v4.1 to v5.0.  Is this still true, or has it been upgraded to handle v5.0 to v5.1?
2. I've followed (I believe) the installation instructions (including reinstalling the RACK CLI at the v5.1 version), and I'm getting an error about a missing module 'rack.commits'.  Any idea if this is an error on my part, or whether there is some piece that may not have made it into the installation?  (Full error below.)

```
$ rack_migrate --log-level=DEBUG --from-folder v5.0 --to-folder v5.1
Traceback (most recent call last):
  File "/home/gnelson/testing/ARCOS/RACK/bin/rack_migrate", line 4, in <module>
    __import__('pkg_resources').run_script('rack-migrate==0.0.0', 'rack_migrate')
  File "/home/gnelson/testing/ARCOS/RACK/lib/python3.7/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/gnelson/testing/ARCOS/RACK/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/home/gnelson/testing/ARCOS/RACK/lib/python3.7/site-packages/rack_migrate-0.0.0-py3.7.egg/EGG-INFO/scripts/rack_migrate", line 23, in <module>
ModuleNotFoundError: No module named 'rack.commits'
```

**Comment by Ptival** [comment]
Hi @GregIthaca sorry I missed this message, feel free to ping me if it ever happens again!

1. is no longer correct and I should update it, the version on master should be able to migrate to the current state of master, give or take the potential commits that may have happened after I last run the migration checker.

2. should not happen, I'm going to look into it!

**Pull request merged**
